version: '3'
services:
  jenkins:
    image: rwlaub/jenkins
    environment:
      - GITHUB_ID=jhernandez5922
      - DOCKERHUB_ID=jhernandez5922
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
